Data Preprocessing is the process of cleaning and converting raw data into a format that can be used by a machine learning model.


In [2]:
with open(
    r"C:\Users\Acer\Documents\LLMs\LLMs\data\the-verdict.txt", encoding="utf-8"
) as f:
    raw_data = f.read()

print("total characters:", len(raw_data))

print(raw_data[:99])

total characters: 20479
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


In [3]:
import re

preprocess = re.findall(r"\b\w+\b", raw_data.lower())
print(preprocess[:30])

['i', 'had', 'always', 'thought', 'jack', 'gisburn', 'rather', 'a', 'cheap', 'genius', 'though', 'a', 'good', 'fellow', 'enough', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', 'in', 'the', 'height', 'of']


In [4]:
print(len(preprocess))

3826


In [5]:
all_words = sorted(set([word for sublist in preprocess for word in sublist]))
vocab_size = len(all_words)
print("vocab size:", vocab_size)

vocab size: 27


In [6]:
vocab = {"<UNK>": 0, **{token: idx + 1 for idx, token in enumerate(all_words)}}

In [7]:
for i, item in enumerate(vocab.items()):
    print(item)
    if i >= 50:
        break

('<UNK>', 0)
('_', 1)
('a', 2)
('b', 3)
('c', 4)
('d', 5)
('e', 6)
('f', 7)
('g', 8)
('h', 9)
('i', 10)
('j', 11)
('k', 12)
('l', 13)
('m', 14)
('n', 15)
('o', 16)
('p', 17)
('q', 18)
('r', 19)
('s', 20)
('t', 21)
('u', 22)
('v', 23)
('w', 24)
('x', 25)
('y', 26)
('z', 27)


In [27]:
import re


class Tokenizer:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {i: s for s, i in vocab.items()}

    def encode(self, text):
        text = text.lower()
        text = re.sub(r"[^\w\s]", "", text)
        tokens = text.split()

        return [
            self.str_to_int.get(token, self.str_to_int["<UNK>"]) for token in tokens
        ]

    def decode(self, ids):
        return " ".join([self.int_to_str[i] for i in ids])

In [9]:
tokenizer = Tokenizer(vocab)

text = """I have mentioned that Mrs. Gisburn was rich; and it was immediately perceptible that her husband was extracting from this circumstance a delicate but substantial satisfaction. It is, as a rule, the people who scorn money who get most out of it; and Jack's elegant disdain of his wife's big balance enabled him, with an appearance of perfect good-breeding, to transmute it into objects of art and luxury. To the latter, I must add, he remained relatively indifferent; but he was buying Renaissance bronzes and eighteenth-century pictures with a discrimination that bespoke the amplest resources."""

ids = tokenizer.encode(text)

print(ids)

[10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0]


In [10]:
print(tokenizer.decode(ids))

i <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> a <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> a <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> i <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> a <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>


In [11]:
all_tokens = sorted(list(set(preprocess)))
all_tokens.extend(["<UNK>", " <|endoftext|>"])
vocab = {token: integer for integer, token in enumerate(all_tokens)}
print(len(vocab.items()))

1086


In [12]:
for i, item in enumerate(list(vocab.items())[-5:]):
    print(item)

('younger', 1081)
('your', 1082)
('yourself', 1083)
('<UNK>', 1084)
(' <|endoftext|>', 1085)


In [13]:
tokenizer = Tokenizer(vocab)
text1 = "This is a test sentence andisnsd."
text2 = "This is a test sentence andisnsd.  This isanothersentence."
text = " <|endoftext|> ".join([text1, text2])
print(text)

This is a test sentence andisnsd. <|endoftext|> This is a test sentence andisnsd.  This isanothersentence.


In [14]:
ids = tokenizer.encode(text)
print(ids)

[945, 507, 15, 1084, 1084, 1084, 1084, 945, 507, 15, 1084, 1084, 1084, 945, 1084]


In [15]:
print(tokenizer.decode(ids))

this is a <UNK> <UNK> <UNK> <UNK> this is a <UNK> <UNK> <UNK> this <UNK>


bite pair encoding


In [16]:
import tiktoken

Tokenizer = tiktoken.get_encoding("gpt2")

In [17]:
text = (
    "Artificial intelligence has transformed modern <|endoftext|> software development, enabling programmers to automate repetitive workflows and analyze enormous datasets efficiently. However, the pseudocryptographic hypertransmogrification engine failed unexpectedly during initialization because the microfluxcapacitor produced unstable quantum-like oscillations. Researchers documented the anomaly carefully before shutting down the entire facility. "
    "Meanwhile, interdisciplinary collaboration between neuroscientists, linguists, and roboticists continues to accelerate innovation across multiple industries. The integration of AI with neuroscience has led to breakthroughs in understanding brain function, while linguistic insights have improved natural language processing algorithms. Roboticists are leveraging these advancements to create more sophisticated and adaptable machines, driving progress in fields such as healthcare, manufacturing, and autonomous systems. As these disciplines converge, the potential for transformative technologies that enhance human capabilities and address complex challenges grows exponentially."
)

integers = Tokenizer.encode(
    text,
    allowed_special={"<|endoftext|>"},
)


print(integers)

[8001, 9542, 4430, 468, 14434, 3660, 220, 50256, 3788, 2478, 11, 15882, 24867, 284, 43511, 28585, 670, 44041, 290, 16602, 9812, 40522, 18306, 13, 2102, 11, 262, 25038, 420, 6012, 6826, 8718, 7645, 76, 519, 38763, 3113, 4054, 25884, 1141, 37588, 780, 262, 4580, 69, 22564, 11128, 330, 2072, 4635, 21354, 14821, 12, 2339, 24969, 602, 13, 26685, 12395, 262, 32172, 7773, 878, 25136, 866, 262, 2104, 6841, 13, 11214, 11, 987, 40625, 12438, 1022, 7669, 25346, 1023, 11, 20280, 1023, 11, 290, 25810, 1023, 4477, 284, 22636, 11044, 1973, 3294, 11798, 13, 383, 11812, 286, 9552, 351, 39738, 468, 2957, 284, 19304, 82, 287, 4547, 3632, 2163, 11, 981, 29929, 17218, 423, 6596, 3288, 3303, 7587, 16113, 13, 3851, 6210, 1023, 389, 42389, 777, 47220, 284, 2251, 517, 13767, 290, 6068, 540, 8217, 11, 5059, 4371, 287, 7032, 884, 355, 11409, 11, 9138, 11, 290, 18284, 3341, 13, 1081, 777, 29861, 47873, 11, 262, 2785, 329, 43590, 8514, 326, 9494, 1692, 9889, 290, 2209, 3716, 6459, 13676, 35529, 13]


In [18]:
strings = Tokenizer.decode(integers)
print(strings)

Artificial intelligence has transformed modern <|endoftext|> software development, enabling programmers to automate repetitive workflows and analyze enormous datasets efficiently. However, the pseudocryptographic hypertransmogrification engine failed unexpectedly during initialization because the microfluxcapacitor produced unstable quantum-like oscillations. Researchers documented the anomaly carefully before shutting down the entire facility. Meanwhile, interdisciplinary collaboration between neuroscientists, linguists, and roboticists continues to accelerate innovation across multiple industries. The integration of AI with neuroscience has led to breakthroughs in understanding brain function, while linguistic insights have improved natural language processing algorithms. Roboticists are leveraging these advancements to create more sophisticated and adaptable machines, driving progress in fields such as healthcare, manufacturing, and autonomous systems. As these disciplines converge,

In [19]:
integers = Tokenizer.encode("hellokxakhabar")
print(integers)
strings = Tokenizer.decode(integers)
print(strings)

[12758, 482, 87, 461, 5976, 283]
hellokxakhabar


Token-Embading


In [20]:
import torch

input_ids = torch.tensor([2, 3, 5, 1])

In [21]:
vocab_size = 6

output_dim = 3

torch.manual_seed(123)

embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [22]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [23]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


input-target pairs


In [24]:
with open(
    r"C:\Users\Acer\Documents\LLMs\LLMs\data\the-verdict.txt", encoding="utf-8"
) as f:
    raw_data = f.read()

In [25]:
preprocess = re.sub(r"[^\w\s]", "", raw_data.lower()).split()

all_tokens = sorted(list(set(preprocess)))

all_tokens.append("<UNK>")

vocab = {token: i for i, token in enumerate(all_tokens)}

In [28]:
tokenizer = Tokenizer(vocab)
encoded_text = tokenizer.encode(raw_data)

print(len(encoded_text))

3613


In [29]:
enc_sample = all_tokens[50:]
print(enc_sample)

['alone', 'along', 'always', 'amazement', 'amid', 'among', 'amplest', 'amusing', 'an', 'and', 'another', 'answer', 'answered', 'any', 'anything', 'anywhere', 'apparent', 'apparently', 'appearance', 'appeared', 'appointed', 'are', 'arm', 'armchair', 'armchairs', 'arms', 'arrt', 'art', 'articles', 'artist', 'as', 'aside', 'asked', 'at', 'atmosphere', 'atom', 'attack', 'attention', 'attitude', 'audacities', 'away', 'awful', 'axioms', 'azaleas', 'back', 'background', 'balance', 'balancing', 'balustraded', 'basking', 'bathrooms', 'be', 'beaming', 'beanstalk', 'bear', 'beard', 'beardas', 'beauty', 'became', 'because', 'becoming', 'bed', 'been', 'before', 'began', 'begun', 'behind', 'behindbecause', 'being', 'believed', 'beneath', 'bespoke', 'better', 'between', 'big', 'bitsi', 'bitterness', 'blocked', 'born', 'borne', 'boudoir', 'bravura', 'break', 'breaking', 'breathing', 'bricabrac', 'briefly', 'brings', 'bronzes', 'brought', 'brown', 'brush', 'bullthat', 'burlington', 'business', 'but', '

In [30]:
context_size = 5

x = enc_sample[:context_size]

y = enc_sample[context_size]

print("input:", x)
print("target:", y)

input: ['alone', 'along', 'always', 'amazement', 'amid']
target: among


In [32]:
for i in range(1, context_size + 1):
    context = enc_sample[:i]
    target = enc_sample[i]

    context_text = " ".join(context)
    target_text = target
    print(tokenizer.encode(context_text), "----->:", tokenizer.encode(target_text))

[50] ----->: [51]
[50, 51] ----->: [52]
[50, 51, 52] ----->: [53]
[50, 51, 52, 53] ----->: [54]
[50, 51, 52, 53, 54] ----->: [55]


In [33]:
for i in range(1, context_size + 1):
    context = enc_sample[:i]

    target = enc_sample[i]

    print("input:", context, "----->:", target)

input: ['alone'] ----->: along
input: ['alone', 'along'] ----->: always
input: ['alone', 'along', 'always'] ----->: amazement
input: ['alone', 'along', 'always', 'amazement'] ----->: amid
input: ['alone', 'along', 'always', 'amazement', 'amid'] ----->: among


Dataset and Dataloader


In [34]:
import torch
from torch.utils.data import Dataset


class GPTDataset(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        token_ids = tokenizer.encode(txt)

        for i in range(0, len(token_ids) - max_length, stride):

            input_chunk = token_ids[i : i + max_length]
            target_chunk = token_ids[i + 1 : i + max_length + 1]

            self.input_ids.append(input_chunk)
            self.target_ids.append(target_chunk)

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return (
            torch.tensor(self.input_ids[idx], dtype=torch.long),
            torch.tensor(self.target_ids[idx], dtype=torch.long),
        )

In [35]:
import tiktoken
from torch.utils.data import DataLoader


def create_data_loader(
    txt,
    batch_size=5,
    max_length=256,
    stride=128,
    shuffle=True,
    drop_last=True,
    num_workers=0,
):

    tokenizer = tiktoken.get_encoding("gpt2")

    dataset = GPTDataset(txt, tokenizer, max_length, stride)

    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers,
    )

    return dataloader

In [36]:
import torch

data_loader = create_data_loader(
    raw_data, batch_size=1, max_length=4, stride=1, shuffle=False
)

data_iter = iter(data_loader)

first_batch = next(data_iter)

x, y = first_batch

print("input ids:", x)
print("target ids:", y)

input ids: tensor([[  40,  367, 2885, 1464]])
target ids: tensor([[ 367, 2885, 1464, 1807]])


Positional embedding:


In [37]:
import torch

vocab_size = 50257
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [38]:
dataloader = create_data_loader(
    txt=raw_data, batch_size=8, max_length=4, stride=4, shuffle=True
)
data_iter = iter(dataloader)
inputs, targets = next(iter(dataloader))

print(inputs)
print(inputs.shape)

tensor([[  339,  4808,  9776,    62],
        [  339,  2993,   655,   644],
        [ 3363,    11,   340,   373],
        [  198,   198,     1,    40],
        [ 6000,  1517,   373,   284],
        [  290,   673,  1297,  8276],
        [ 1139,  2063,   262,   640],
        [  663,   588,   757, 13984]])
torch.Size([8, 4])


In [39]:
token_embeddings = token_embedding_layer(inputs)
print(token_embeddings.shape)

torch.Size([8, 4, 256])


In [40]:
max_length = 4
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)
pos_embadings = pos_embedding_layer(torch.arange(context_length))
print(pos_embadings.shape)

torch.Size([4, 256])


token-embedding


In [41]:
import torch

input_ids = torch.tensor([2, 3, 5, 1])

In [42]:
vocab_size = 6

output_dim = 3

torch.manual_seed(123)

embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [43]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [44]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)
